import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const BuildsPage: NextPage = () => {
  const builds = api.builds.getBuilds.useQuery();

  return (
    <>
      <Head>
        <title>AOE4 BUILDS LIST</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffff00] to-[#15162c] gap-6" >
        <h1>Builds</h1>
        <Link className="border p-2" href="/"> Home</Link>
        <Link className="border p-2" href="/submit-build"> Submit a new Build</Link>

        <table>
            <thead>
                <th>ID</th>
                <th>Civilization</th>
                <th>Build</th>
            </thead>
            <tbody>
                {builds.data?.map((build) => (
                <tr key={build.id}>
                    <td>{build.id}</td>
                    <td>{build.civilization}</td>
                    <td>{build.build}</td>
                </tr>
                   ));  
                }
            </tbody>
        </table>
    
      </main>
    </>
  );
};

export default BuildsPage;

