import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const HomePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>AOE4 BUILD ORDER</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <img src="/aoe4/wolf2.gif" className="absolute top-0 left-0 animate-slide-right h-[200px] w-[200px] animation-duration-2000 animation-iteration-count-infinite" alt="" /> */}
      <main className="flex min-h-screen flex-col items-center  gap-6   text-black dark:bg-gray-800 dark:text-white " >



{/* <h2 className=" text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-6xl mt-5 dark:text-white"> */}
{/* Make an awesome build and conquer the battlefield!</h2> */}
{/* <p className="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">
    Here at Flowbite we focus on markets where technology, innovation, and capital can unlock long-term value and drive economic growth.</p> */}
<Link href="/builds" >
<p  className="inline-flex items-center mt-5 justify-center px-5 py-3 text-base font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
    Discover Builds
    <svg className="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
</p>
            </Link>
    


    <img  src="/aoe4/jumpdown.gif" className="object-cover w-full rounded-t-lg  md:h-auto md:w-40 md:rounded-none md:rounded-l-lg"  alt=""/> 
        {/* <a href="#" className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    <img  src="warrior.svg" className="object-cover w-full rounded-t-lg h-60 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"  alt=""/> 
    <div className="flex flex-col justify-between p-4 leading-normal">
        <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Create or Find an Awesome Build</h5>
        <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
            Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>


    </div>
</a> */}


<div className="flex flex-wrap justify-between gap-10">
    
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            {/* <svg className="w-10 h-10 mb-2 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M5 5a3 3 0 015-2.236A3 3 0 0114.83 6H16a2 2 0 110 4h-5V9a1 1 0 10-2 0v1H4a2 2 0 110-4h1.17C5.06 5.687 5 5.35 5 5zm4 1V5a1 1 0 10-1 1h1zm3 0a1 1 0 10-1-1v1h1z" clipRule="evenodd"></path><path d="M9 11H3v5a2 2 0 002 2h4v-7zM11 18h4a2 2 0 002-2v-5h-6v7z"></path></svg> */}
            <img  src="sword.svg" className="object-cover w-full rounded-t-lg h-60 md:h-auto md:w-24 md:rounded-none md:rounded-l-lg"  alt=""/> 

            <a href="#">
                <h5 className="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">Create your build, and leave your mark</h5>
            </a>
            <p className="mb-3 font-normal text-gray-500 dark:text-gray-400">Share your awesome idea with the Community, and get great awards</p>

        </div>
    {/* </div> */}
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            {/* <svg className="w-10 h-10 mb-2 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M5 5a3 3 0 015-2.236A3 3 0 0114.83 6H16a2 2 0 110 4h-5V9a1 1 0 10-2 0v1H4a2 2 0 110-4h1.17C5.06 5.687 5 5.35 5 5zm4 1V5a1 1 0 10-1 1h1zm3 0a1 1 0 10-1-1v1h1z" clipRule="evenodd"></path><path d="M9 11H3v5a2 2 0 002 2h4v-7zM11 18h4a2 2 0 002-2v-5h-6v7z"></path></svg> */}
            <img  src="simple-indian-arrows.svg" className="object-cover w-full rounded-t-lg h-60 md:h-auto md:w-24 md:rounded-none md:rounded-l-lg"  alt=""/> 

            <a href="#">
                <h5 className="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">Explore builds from different players</h5>
            </a>
            <p className="mb-3 font-normal text-gray-500 dark:text-gray-400">Go to this step by step guideline process on how to certify for your weekly benefits:</p>

        </div>
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            {/* <svg className="w-10 h-10 mb-2 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M5 5a3 3 0 015-2.236A3 3 0 0114.83 6H16a2 2 0 110 4h-5V9a1 1 0 10-2 0v1H4a2 2 0 110-4h1.17C5.06 5.687 5 5.35 5 5zm4 1V5a1 1 0 10-1 1h1zm3 0a1 1 0 10-1-1v1h1z" clipRule="evenodd"></path><path d="M9 11H3v5a2 2 0 002 2h4v-7zM11 18h4a2 2 0 002-2v-5h-6v7z"></path></svg> */}
            {/* <img  src="sword.svg" className="object-cover w-full rounded-t-lg h-60 md:h-auto md:w-24 md:rounded-none md:rounded-l-lg"  alt=""/>  */}
            <img  src="/aoe4/arrows.gif" className="object-cover w-full rounded-t-lg  md:h-auto md:w-40  md:rounded-none md:rounded-l-lg"  alt=""/> 

            <a href="#">
                <h5 className="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">Vote and promote individual builds</h5>
            </a>
            <p className="mb-3 font-normal text-gray-500 dark:text-gray-400">If you find a build useful, give it a rating. That build might become new Meta. </p>

        </div>
</div>






      </main>
    </>
  );
};

export default HomePage;


