import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const HomePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>AOE4 BUILD ORDER</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center  gap-6   text-black dark:bg-gray-800 dark:text-white " >
        <h1>Welcome to AoE 4 Build Order Site</h1>
        {/* <Link className="border p-5" href="/submit-build"> Submit a new Build</Link>
        <Link className="border p-5" href="/builds"> Show all Builds</Link> */}

      </main>
    </>
  );
};

export default HomePage;


