import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useState } from "react";

const Home: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();
  const [civilization, setCivilization] = useState("Chinese");
  const [build, setBuildOrder] = useState("");

  async function handleSubmitBuildOrder (e: React.FormEvent) {
    // console.log(Buildorder)
    // console.log(Civilization)
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      civilization,
      build,
    })
  }
  return (
    <>
      <Head>
        <title>AOE4 BUILD ORDER</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffff00] to-[#15162c] gap-6" >
        <h1>Welcome to AoE 4 Build Order Site</h1>
        <Link className="border p-5" href="/submit-build"> Submit a new Build</Link>
        <Link className="border p-5" href="/builds"> Show all Builds</Link>

      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
