import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


import { api } from "~/utils/api";
import { useState } from "react";

const SubmitPage: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();
  const [civilization, setCivilization] = useState("Chinese");
  const [build, setBuildOrder] = useState("");

  async function handleSubmitBuildOrder (e: React.FormEvent) {

    e.preventDefault();
    await createBuildMutation.mutateAsync({
      civilization,
      build,
    })
  }
  return (
    <>
      <Head>
        <title>Submit Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6 text-black dark:bg-gray-800 dark:text-black " >
      
     
        <form className="flex flex-col items-center  gap-4  " onSubmit={handleSubmitBuildOrder}>
        <label  className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Civilization</label>

          <select 
           className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            value={civilization}  
            onChange={(e) => setCivilization(e.target.value)}
            id="select-civ" 
            required> 
            <option value="Holy Roman Empire">Holy Roman Empire</option>
            <option value="Rus">Rus</option>
            <option value="Chinese">Chinese</option>
            <option value="English">English</option>
            <option value="French">French</option>
            <option value="Mongols">Mongols</option>
            <option value="Delhi Sultanate">Delhi Sultanate</option>
            <option value="Abbasid Dynasty">Abbasid Dynasty</option>
            <option value="Ottomans">Ottomans</option>
          </select>
          <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your message</label>

          <textarea value={build} onChange={(e) => setBuildOrder(e.target.value)} required  
          className="block p-2.5 w-[500px] h-[200px] text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ></textarea>
          <button className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit Build</button>
        </form>
      
      </main>
    </>
  );
};

export default SubmitPage;


