import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


import { api } from "~/utils/api";
import { useState } from "react";

const SubmitPage: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();
  const [civilization, setCivilization] = useState("Chinese");
  const [typee, setType] = useState("Fast Cavalry");
  const [desc, setDesc] = useState("");
  const [build, setBuildOrder] = useState("");
  const [isOpen, setIsOpen] = useState(false);

  // const [civilization, setCivilization] = useState("Chinese");
  // const [build, setBuildOrder] = useState("");

  function openModal() {
  setIsOpen(true);

}

function closeModal() {
  setIsOpen(false);
}


  async function handleSubmitBuildOrder (e: React.FormEvent) {

    e.preventDefault();
    await createBuildMutation.mutateAsync({
      civilization,
      typee,
      desc,
      build,

    })
    console.log('Build Created')
    openModal();
  }
  return (
    <>
      <Head>
        <title>Submit Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-row items-center justify-center gap-6 text-black dark:bg-gray-800 dark:text-black " >
      <div className=" flex justify-center basis-1/3">
      <img  src="/aoe4/croco.gif"  className="mb-[150px]"  alt=""/> 

      </div>
     
      <div  className=" basis-1/2">
        <form className="flex flex-col items-center  gap-4  " onSubmit={handleSubmitBuildOrder}>
        <label  className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
          Select Civilization</label>
          {/* <img src="/aoe4/rus.png" alt="Rus icon" className="w-6 h-6 mr-2"/>  */}

          <select 
           className="w-[80%] bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 appearance-none"
            value={civilization}  
            onChange={(e) => setCivilization(e.target.value)}
            id="select-civ" 
            required> 

            <option value="Chinese">Chinese</option>
            <option value="Rus">Rus</option>
            <option value="English">English</option>
            <option value="French">French</option>
            <option value="Mongols">Mongols</option>
            <option value="Delhi Sultanate">Delhi Sultanate</option>
            <option value="Abbasid Dynasty">Abbasid Dynasty</option>
            <option value="Ottomans">Ottomans</option>
          </select>
          {/* src={`/aoe4/${selectedBuild.civilization.toLowerCase()}.png`} */}
          {/* aoe4-builder-order\public/aoe4/Holy Roman Empire.png */}
        <label  className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Build Type</label>

          <select 
           className="w-[80%] bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            value={typee}  
            onChange={(e) => setType(e.target.value)}
            id="select-type" 
            required> 
            <option value="Pro Build">Pro Build</option>
            <option value="Beginner Build">Beginner Build</option>
            <option value="Any Elo">Any Elo</option>
            <option value="LSC BROs">LSC BROs</option>
          </select>
          <label className="block  text-sm font-medium text-gray-900 dark:text-white">Short Description </label>
          <textarea value={desc} onChange={(e) => setDesc(e.target.value)} required  
          className="block p-2.5 w-[80%] h-[80px] text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" >            
          </textarea>
          <label className="block  text-sm font-medium text-gray-900 dark:text-white">Full Build</label>
          <textarea value={build} onChange={(e) => setBuildOrder(e.target.value)} required  
          className="block p-2.5 w-[80%] h-[200px] text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" >            
          </textarea>
          <button className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit Build</button>
        </form>
      </div>
      {/* <div className="flex justify-center basis-1/3"> */}
      {/* <img  src="/aoe4/dog.gif"   alt=""/>  */}


      
      {/* </div> */}

      {/* MODAL */}
      {isOpen   &&  (
                    <div className=" fixed top-0 left-0 right-0 bottom-0 flex items-center justify-center ">
                    <div className=" flex flex-col p-6 w-[60%] justify-center items-center   bg-white border-8	 border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700" >
                        {/* <h2 className="text-lg font-bold mb-4">Whole Build </h2> */}
                        {/* <h1 className="mb-4 ">    Success</h1> */}
                        <h2 className=" text-3xl mb-5 font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-6xl dark:text-white">
                        Build Created !</h2>
                        {/* <img className="  h-[120px] w-[250px] mb-5"  src={`/aoe4/${selectedBuild.civilization.toLowerCase()}.png`} alt="" /> */}
                        <img  src="/aoe4/rdy.gif"   alt=""/> 

                        {/* <p className="mb-4  "> DESCRIPTION:  </p> */}
                        {/* <p className="m-5 font-extrabold dark:text-white ">BUILD ORDER DETAILS:</p> */}
                        
                        <button   onClick={closeModal} className=" mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                           Close</button>
    
                    </div>
                    </div>
                )}

      </main>
    </>
  );
};

export default SubmitPage;


